#Finished March 2021

#Perceptron that identifies points as being on one or the other side of a line in a plane
#Structured like this (Perceptron):
#
# O -
#     O
# O -

import createPoints
import random

if __name__=='__main__':
    #Establish variables, training and data sets, and weights and biases
    m = 1; b = 0; lr = 0.02; lB = -100; uB = 100
    trainingSet = createPoints.doTheThing(500000, lB, uB, m, b)
    testingSet = createPoints.doTheThing(10000, lB, uB, m, b)
    weights = [float(random.randrange(-10,10))/10, float(random.randrange(-10,10))/10]
    biases = [float(random.randrange(-10,10))/10]

    #Iterate through all test points and adjust weights and biases
    for i in trainingSet:
        sum = 0
        for k in range(len(i)-1): sum += float(weights[k])*float(i[k])
        sum += biases[0]
        sum = round(sum, 6)
        print(sum)
        if sum >= 0: sum = 1
        else: sum = -1
        if sum != i[2]:
            weights[0] = round(weights[0] + lr * i[2] * i[0], 6)
            weights[1] = round(weights[1] + lr * i[2] * i[1], 6)
            biases[0] = round(biases[0] + lr * i[2], 6)
        print('Weights: ', weights)
        print('Biase: ', biases)
        print('\n')

    #Calculating line generated by code
    var = (biases[0] * -1 + weights[0] * -1 * 0) / weights[1]
    var2 = (biases[0] * -1 + weights[0] * -1 * 1) / weights[1]
    slopeGuess = round(((var2 - var) / (1 - 0)), 2)

    #Testing final weights and biases
    percentageSum = 0
    for i in testingSet:
        for k in range(len(i)-1): sum += float(weights[k])*float(i[k])
        sum += biases[0]
        if sum >= 0: sum = 1
        else: sum = -1
        if sum == i[2]: percentageSum += 1
    percentage = round((percentageSum/len(testingSet)*100), 2)

    #Printing final stuff
    print('--------------------------------')
    print('Final Weights: ', weights)
    print('Final Bias: ', biases, '\n')
    print('Actual Equation: y=' + str(m) + 'x+' + str(b))
    print('Guessed Equation: y=' + str(slopeGuess) + 'x+' + str(round(var, 2)) + '\n')
    print('Success: ' + str(percentage) + '%')